version: build{build}

platform:
  - x64

os: Visual Studio 2015

cache:
  - node_modules -> appveyor.yml

install:
  - ps: Install-Product node LTS $env:platform
  - node --version
  - npm --version
  - python --version
  - npm ci

build: off

test_script:
  - npm run test
  # - npm run test-e2e
